spring.application.name=nutra
server.port=8080
server.servlet.context-path=/api
jwt.secretKey=dlkfjd2434jh3jh3oh388dfd78324e8r5y89237458390jknbvjldshr3084

spring.datasource.url=jdbc:mysql://localhost:3306/neutra
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


